### ISSUE TITLE
ERROR: Valid Through is not required

### ISSUE THREAD

**Issue by Teisi** [pegasuswerbeagentur/google_for_jobs#12]
If you leave this field empty then TYPO3 shows error:

Return value of Pegasus\GoogleForJobs\Domain\Model\Job::getValidThrough() must be an instance of DateTime, null returned.

So it has to be required, i think (TCA).

**Comment by Micha-sus** [comment]
Hi @Teisi ,

since Google is requiring this field to be optional, the getter was changed to use null as a valid return type in the latest releases:

- TYPO3 10: https://github.com/pegasuswerbeagentur/google_for_jobs/tree/2.1.0
- TYPO3 9: https://github.com/pegasuswerbeagentur/google_for_jobs/tree/1.5.0
